language: ruby
cache: bundler
install:
- bundle install
script:
- "make deploy"
env:
  global:
    secure: b4M1GCAXzpFdzMw3ISdujlzTaC3VH3QdXmCxGGpEmmNBiOdeEehMB+NnZEEIr/9/bsyXPxkF3e5DZCbSUJSx1nPsdB8uGq3Y5RzGDm4QgRZLVwcDgZ1glFwmoAdyU1WT2AYeMGO3ksmgqTPIE1VM0Xx7NrmsHcHMLV3Mt7ygEeckRZ0qNwM6xtLI8Z2NiuLhVtAow6aDzRKJsUNzVRbDqpywQm2DjK8RBQTnm3gRdv27PzrVtKVv/7akC9uww1VJYv3BmPyNXlY49ju81XEF0EuCzq6yfj87T477UItnLLSjYh8SoPDyYVVaOqbcO5tFR4rOm+72Mx1C9eYDNMRp6FuRDUcHLBYFIkWuGRIStFof1apkmFAPGUz2H6dlFoEFXK5kcN8eZ1cKZ8HXPDRLsBBhOBXKs5L/B7k8S5ZT4drj+6Atox/bZGO3m8+Pfx6HAqsMVpSaVrS4uW68oh0GYy0YHLVi08+TX3noNf5SJEMt2Tbx5xy5kykGcrmAttGv3KDcseT1fpvBioWsgOc/SO9ftKEYcBbu7dVivN98v2mAACUKS5DKbmCv0bz++UbxkfyXE2fwVsjguhGqNet/HySOTU+M0a9GygraeOcLyYWU9bl+njjvjT7NKh72dIhFCO2fW1v6QsfGWOQwJHRdYXiBk2nHhzMoAS9lTeUXbgU=
