# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems: [jekyll-paginate]


# Setup
title:            Owen Rumney
tagline:          Software Developer
description:
url:              http://www.owenrumney.co.uk
baseurl:          /

author:
  name:           'Owen Rumney'
  url:            https://twitter.com/owenrum

paginate:         5

# Custom vars
version:          2.1.0
