# Dependencies
markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]

# Setup
title: Owen Rumney
tagline: Software Developer
description:
url: http://www.owenrumney.co.uk
baseurl: /
permalink: pretty

author:
  name: "Owen Rumney"
  url: https://twitter.com/owenrum

paginate: 5

# Custom vars
version: 2.1.0
